name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Buildozer Action
        uses: SubspaceShare/android-buildozer-action@v1.1.1
        with:
          workdir: .
          command: buildozer android debug
